#!/bin/bash
cd /home/ubuntu/NTRTsim/build/dev/dariostuff/directional_jump

./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.5
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.48
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.46
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.44
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.42
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.4
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.38
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.36
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.34
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.32
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.3
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.28
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.26
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.24
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.22
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.2
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.18
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.16
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.14
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.12
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.1
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.08
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.06
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.04
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.02
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 0.0
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.02
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.04
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.06
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.08
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.1
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.12
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.14
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.16
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.18
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.2
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.22
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.24
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.26
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.28
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.3
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.32
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.34
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.36
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.38
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.4
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.42
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.44
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.46
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.48
./AppisocDarYAMLdir /home/ubuntu/NTRTsim/src/dev/dariostuff/models/isodrop3Aextalligned.yaml 1.0 0.5 1 6 -0.5
